services:
  - type: web
    name: trading-bot-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web.py

  - type: worker
    name: trading-bot-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
