services:
  - type: web
    name: nyah-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    envVars:
      - key: DASHBOARD_PASSWORD
        value: Elysee01
      - key: ALERT_EMAIL_TO
        value: jeanjerome564@gmail.com
      - key: ALERT_SMS_EMAIL_TO
        value: 7725198965@vtext.com
      - key: ALERT_MMS_EMAIL_TO
        value: 7725198965@vzwpix.com
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: USE_TWILIO
        value: "false"
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: OWNER_PHONE_E164
        value: +17725198965
      - key: TZ
        value: America/New_York
  - type: worker
    name: nyah-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: DASHBOARD_PASSWORD
        value: Elysee01
      - key: ALERT_EMAIL_TO
        value: jeanjerome564@gmail.com
      - key: ALERT_SMS_EMAIL_TO
        value: 7725198965@vtext.com
      - key: ALERT_MMS_EMAIL_TO
        value: 7725198965@vzwpix.com
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: USE_TWILIO
        value: "false"
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: OWNER_PHONE_E164
        value: +17725198965
      - key: TZ
        value: America/New_York
